name: smart_app
description: "The SMART GD now on your hands."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_masked_text2: ^0.9.1
  http: ^1.2.2
  shared_preferences: ^2.0.0
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
  - assets/logo_login.png
  - assets/logo.png
  - assets/logo_white_sm.png

  uses-material-design: true
